// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  GENERATED FILE — DO NOT EDIT.                                           ║
// ║  Source: app/lib/ebay-dom.js   Regenerate: npm run ext:build             ║
// ║  Edits here are silently overwritten and will make the extension and the ║
// ║  server disagree about how to read eBay.                                 ║
// ╚══════════════════════════════════════════════════════════════════════════╝

// ─── eBay sold-page contract: THE single source of truth ─────────────────────
//
// Everything in this file describes how eBay's sold-results page is SHAPED right now:
// which elements hold a result, where the title and price live inside one, and what a
// refusal (sign-in wall / bot challenge) looks like. That shape is the most volatile
// thing this product depends on — eBay has changed the card layout three separate times
// and each change silently zeroed out comps until someone noticed.
//
// It lives in a dependency-free ES module because TWO very different runtimes have to
// agree on it exactly:
//   • the Next server (app/lib/ebay.ts), which parses with cheerio, and
//   • the browser extension (extension/lib/ebay-dom.js), which parses with DOMParser
//     inside the user's own signed-in eBay session.
// If those two ever disagree, the same product scores differently depending on which
// path served it — so the selectors, the regexes, the price rules and the query builder
// are defined ONCE here and imported by both. The extension's copy is generated by
// `npm run ext:build`; never hand-edit it.
//
// Rule for the next layout change: fix it HERE, re-run the build, ship both.

// ─── Card layout selectors ───────────────────────────────────────────────────
// eBay serves three card layouts depending on session/rollout and A/B tests, so we match
// whichever appears rather than betting on one:
//   • legacy  <li class="s-item">            title .s-item__title      price .s-item__price
//   • interim <li class="s-card">            title .s-card__title      price .s-card__price
//   • newer   <div class="su-card-container"> title .su-item-card__title price .su-item-card__price
// The signed-in browser session tends to get the newer su-card layout; server-side
// scrapes tended to get the legacy one.
export const CARD_SELECTOR = 'li.s-card, li.s-item, .su-card-container';
export const TITLE_SELECTOR = '.s-card__title, .s-item__title, .su-item-card__title';
export const PRICE_SELECTOR = '.s-card__price, .s-item__price, .su-item-card__price';

// Last-ditch selectors for a layout we haven't seen yet. Deliberately loose: a card we
// half-read is better than a card we drop, and parsePrice rejects anything nonsensical.
export const TITLE_FALLBACK = '[class*="title"]';
export const PRICE_FALLBACK = '[class*="price"]';

// ─── Fuzzy-filler divider ────────────────────────────────────────────────────
// When a search has FEW or NO exact matches, eBay pads the page with a "Results matching
// fewer words" section of unrelated same-category items. Counting those as comps invents
// an entire fake sold history (fake median, fake volume, fake ROI) for a product with no
// resale market — the single most dangerous wrong answer this product can give, because
// the user acts on it. Real exact matches always render BEFORE the divider, so we cut the
// HTML there before parsing.
export const FUZZY_DIVIDER =
  /No exact matches found|Results matching fewer words|Results that closely match|matching fewer words/i;

// eBay renders the divider as a heading BETWEEN cards, not inside one — but a card that
// does contain it means we've run past the exact matches, so the per-card loop breaks on
// this as defense-in-depth.
export const DIVIDER_IN_CARD = /Results matching fewer words|Results that closely match/i;

// The "Shop on eBay" promo placeholder is a card with no real listing behind it.
export const PROMO_TITLE = /Shop on eBay/i;

// ─── Refusal detection ───────────────────────────────────────────────────────
// eBay's sign-in wall on sold/completed searches (live since 2026-07): a signed-out
// request 200s and returns "Sign in or Register" with ZERO result cards, which is
// indistinguishable from "this item genuinely never sold" unless we look for it.
// Detecting it is what keeps a wall from being reported as NO MARKET.
export const SIGNIN_TITLE = /sign in or register/;
export const SIGNIN_HOST = /https:\/\/signin\.ebay\.[a-z.]+\//i;

// Bot challenge / error interstitial. Data is worthless AND it means back off.
export const THROTTLE_TITLE =
  /error page|interruption|are you a human|robot|access denied|pardon our interruption|unusual traffic/;
export const THROTTLE_BODY =
  /pardon the interruption|verify you('| a)re a human|unusual activity from your/i;

// How much of the document we scan for the URL/body markers above. The markers live in
// the head or the opening banner; scanning the whole page would be slower and noisier.
const HEAD_SLICE = 4000;

/**
 * Classify a fetched page as a refusal, or null if it looks like real results.
 * @param {string} html   full page HTML
 * @param {string} title  text of <title>, lowercased by the caller or not
 * @returns {'blocked'|'throttled'|null}
 */
export function classifyPage(html, title) {
  const t = (title || '').toLowerCase();
  const head = (html || '').slice(0, HEAD_SLICE);
  if (SIGNIN_TITLE.test(t) || SIGNIN_HOST.test(head)) return 'blocked';
  if (THROTTLE_TITLE.test(t) || THROTTLE_BODY.test(head)) return 'throttled';
  return null;
}

/** Cut the page at the fuzzy-match divider so filler cards are never parsed. */
export function stripFuzzyFiller(html) {
  const m = FUZZY_DIVIDER.exec(html);
  return m ? html.slice(0, m.index) : html;
}

/**
 * Parse a price cell. Rejects ranges ("$5 to $9" — a range tells us nothing about what
 * one unit sold for) and values outside a sane band, which filters out parse accidents
 * like shipping-only cells and $12,000 bulk pallets.
 * @param {string} raw
 * @returns {number|null}
 */
export function parsePrice(raw) {
  if (!raw || raw.indexOf(' to ') !== -1) return null;
  const m = raw.match(/[\d,]+\.?\d*/);
  if (!m) return null;
  const p = parseFloat(m[0].replace(/,/g, ''));
  return p >= 1 && p < 5000 ? p : null;
}

/**
 * Turn one card's raw title/price text into an item, or null if it isn't a real comp.
 * Both parsers funnel every card through here, so "what counts as a listing" is decided
 * in exactly one place.
 * @param {string} titleText
 * @param {string} priceText
 * @returns {{title: string, price: number}|null}
 */
export function itemFromCard(titleText, priceText) {
  const title = (titleText || '').trim();
  if (!title || PROMO_TITLE.test(title)) return null;
  const price = parsePrice((priceText || '').trim());
  if (price == null) return null;
  return { title, price };
}

/**
 * Parse sold items out of a real DOM Document. Used by the extension, where the page was
 * fetched inside the user's signed-in eBay session and parsed with DOMParser.
 * Never called on the server — Node has no DOMParser — but it lives here so both
 * parsers share one definition of the layout.
 * @param {Document} doc
 * @returns {{title: string, price: number}[]}
 */
export function parseItemsFromDocument(doc) {
  const items = [];
  const cards = doc.querySelectorAll(CARD_SELECTOR);
  for (const card of cards) {
    if (DIVIDER_IN_CARD.test(card.textContent || '')) break; // past the exact matches
    const titleEl = card.querySelector(TITLE_SELECTOR) || card.querySelector(TITLE_FALLBACK);
    const priceEl = card.querySelector(PRICE_SELECTOR) || card.querySelector(PRICE_FALLBACK);
    const item = itemFromCard(titleEl?.textContent || '', priceEl?.textContent || '');
    if (item) items.push(item);
  }
  return items;
}

// ─── Query building ──────────────────────────────────────────────────────────
//
// Store product titles are marketing copy; eBay search is literal. These words appear in
// half of all product names and match nothing useful on eBay, so they're stripped before
// the search — otherwise "Free Shipping" and "Satisfaction Guarantee" dilute the query
// and the real identifying words fall off the end of the length cap.
const NOISE_WORDS = new Set([
  'gift', 'gifts', 'set', 'sets', 'bundle', 'bundles', 'pack', 'packs', 'variety',
  'sample', 'samples', 'single', 'serve', 'option', 'options', 'video', 'value',
  'satisfaction', 'guarantee', 'guaranteed', 'days', 'day', 'free', 'shipping',
  'bonus', 'deal', 'sale', 'official', 'authentic', 'brand', 'the', 'and', 'with',
  'for', 'your',
]);

/** Strip punctuation, parentheticals, bare numbers and noise words from a product title. */
export function cleanWords(query) {
  return String(query || '')
    .toLowerCase()
    .replace(/\(.*?\)/g, ' ')
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 1 && !/^\d+$/.test(w) && !NOISE_WORDS.has(w));
}

// Cap on how many words go into the eBay search. The brand stays first, so trimming the
// tail keeps identity and drops description.
const MAX_QUERY_WORDS = 6;

/**
 * The exact keywords + relevance tokens for a product title.
 *
 * The extension searches eBay for `keywords` and the server scores the results against
 * `tokens`. Both are derived HERE from the same input so the two sides can't drift: if
 * the extension searched a differently-cleaned string than the server scored against,
 * relevance would silently mis-fire on every lookup.
 * @param {string} query
 * @returns {{keywords: string, tokens: string[]}}
 */
export function buildQuery(query) {
  const words = cleanWords(query);
  const keywords = words.slice(0, MAX_QUERY_WORDS).join(' ');
  return { keywords, tokens: cleanWords(keywords) };
}

/** eBay sold-search URL. `_sop=13` = ended recently, so comps skew fresh. */
export function buildSearchUrl(keywords) {
  const qs = new URLSearchParams({
    _nkw: keywords,
    LH_Complete: '1',
    LH_Sold: '1',
    _sacat: '0',
    _ipg: '60',
    _sop: '13',
  });
  return `https://www.ebay.com/sch/i.html?${qs}`;
}
